/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package forms;

import com.raven.chart.ModelChart;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;

/**
 *
 * @author yoaim
 */
public class BarChartForm extends javax.swing.JPanel {

    /**
     * Creates new form BarChartForm
     */
    public BarChartForm() {
        initComponents();
        //chart.addLegend("Income", new Color(245, 189, 135));
        //chart.addLegend("Expense", new Color(135, 189, 245));
        //chart.addLegend("Profit", new Color(189, 135, 245));
        chart.addLegend("Years", new Color(34, 40, 44));
       // chart.addData(new ModelChart("January", new double[]{50, 0, 0,0}));
        //chart.addData(new ModelChart("February", new double[]{60, 0, 0,0}));
        //chart.addData(new ModelChart("March", new double[]{20, 0, 0,0}));
        //chart.addData(new ModelChart("April", new double[]{48, 0, 0,0}));
        //chart.addData(new ModelChart("May", new double[]{35, 0, 0,0}));
        //chart.addData(new ModelChart("June", new double[]{19, 0, 0,0}));
        String query = "select count(id),EXTRACT(year FROM date_debut) from reservation group by EXTRACT(year FROM date_debut);";
		try {
                   PreparedStatement preparedStatement = connexion.Connexion.getConnection().prepareStatement(query);
			ResultSet resultSet = preparedStatement.executeQuery();
                        while(resultSet.next()){
                         //dataset.setValue(resultSet.getInt(1), "client",resultSet.getString(2)); 
                         chart.addData(new ModelChart(resultSet.getString("EXTRACT(year FROM date_debut)"), new double[]{resultSet.getInt("COUNT(id)"), 0, 0,0}));
                        }
		} catch (SQLException e) {
			e.printStackTrace();
		}
   
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        chart = new com.raven.chart.Chart();
        jLabel1 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Century Gothic", 1, 10)); // NOI18N
        jLabel1.setText("Nombre de client");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(92, 92, 92)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(chart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(chart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private com.raven.chart.Chart chart;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
