/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package forms;

import entities.Chambre;
import entities.Client;
import java.util.Date;
import javax.swing.table.DefaultTableModel;
import service.CategorieService;
import service.ChambreService;
import service.ClientService;

/**
 *
 * @author yoaim
 */
public class BetweenDateForm extends javax.swing.JPanel {

    /**
     * Creates new form BetweenDateForm
     */
     private CategorieService categorieService ;
    private ChambreService chambreService;
    private ClientService clientService;
    private DefaultTableModel model;
    private static int id;
    
    public BetweenDateForm() {
        initComponents();
        chambreService = new ChambreService();
        model=(DefaultTableModel)listChambre.getModel();
        clientService = new ClientService();
        loadList();
    }
    

     private void loadList() {
        for (Client c : clientService.findAll()) {
            combobox1.addItem(c);
        }
     }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDateChooser1 = new com.toedter.calendar.JDateChooser();
        jDateChooser2 = new com.toedter.calendar.JDateChooser();
        combobox1 = new combobox.Combobox();
        jScrollPane2 = new javax.swing.JScrollPane();
        listChambre = new table.Table();
        ajouterbtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        combobox1.setLabeText("Client");
        combobox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                combobox1ActionPerformed(evt);
            }
        });

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        listChambre.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Télephone", "Catégorie"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listChambre.setToolTipText("");
        listChambre.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listChambreMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listChambre);

        ajouterbtn.setBackground(new java.awt.Color(21, 25, 28));
        ajouterbtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ajouterbtn.setForeground(new java.awt.Color(255, 255, 255));
        ajouterbtn.setText("Chercher");
        ajouterbtn.setPreferredSize(new java.awt.Dimension(150, 40));
        ajouterbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterbtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 507, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(combobox1, javax.swing.GroupLayout.PREFERRED_SIZE, 209, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 100, Short.MAX_VALUE)
                .addComponent(jDateChooser1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(ajouterbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(100, 100, 100))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(combobox1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jDateChooser2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(26, 26, 26)
                .addComponent(ajouterbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(138, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void listChambreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listChambreMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_listChambreMouseClicked

    private void combobox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_combobox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_combobox1ActionPerformed

    private void ajouterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterbtnActionPerformed
        // TODO add your handling code here:
         Client client = (Client) combobox1.getSelectedItem();
        Date dateDebut = jDateChooser1.getDate();
        Date dateFin = jDateChooser2.getDate();
          model.setRowCount(0);
        for(Chambre c : chambreService.findChambreBetweenDates(client, dateDebut, dateFin)){
            model.addRow(new Object[]{c.getId(),c.getTelephone(),c.getCategorie()});
        }
    }//GEN-LAST:event_ajouterbtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterbtn;
    private combobox.Combobox combobox1;
    private com.toedter.calendar.JDateChooser jDateChooser1;
    private com.toedter.calendar.JDateChooser jDateChooser2;
    private javax.swing.JScrollPane jScrollPane2;
    private table.Table listChambre;
    // End of variables declaration//GEN-END:variables
}
