/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package forms;

import com.sun.org.apache.bcel.internal.generic.AALOAD;
import java.awt.Color;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javaswingdev.chart.ModelPieChart;
import javaswingdev.chart.PieChart;
import service.CategorieService;

/**
 *
 * @author yoaim
 */
public class ChartForm extends javax.swing.JPanel {

    /**
     * Creates new form ChartForm
     */
    public ChartForm() {
        initComponents();
        CategorieService categorieService = new CategorieService();
        
        pieChart1.setChartType(PieChart.PeiChartType.DONUT_CHART);
        //pieChart1.addData(new ModelPieChart("Tigher", 150, new Color(23, 126, 238)));
        //pieChart1.addData(new ModelPieChart("ABC", 100, new Color(221, 65, 65)));
        //pieChart1.addData(new ModelPieChart("Coca", 1, new Color(47, 157, 64)));
        //pieChart1.addData(new ModelPieChart("Vita", 150, new Color(196, 151, 58)));
         String query = "SELECT COUNT(id), categorie_id FROM chambre GROUP BY categorie_id;";
		try {
                   PreparedStatement preparedStatement = connexion.Connexion.getConnection().prepareStatement(query);
			ResultSet resultSet = preparedStatement.executeQuery();
                        while(resultSet.next()){
                         //dataset.setValue(resultSet.getInt(1), "client",resultSet.getString(2)); 
                         pieChart1.addData(new ModelPieChart(categorieService.findById(resultSet.getInt("categorie_id")).getLibelle(), resultSet.getInt("COUNT(id)"), new Color((int)(Math.random() * 0x1000000))));
                        }
		} catch (SQLException e) {
			e.printStackTrace();
		}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pieChart1 = new javaswingdev.chart.PieChart();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 550));

        pieChart1.setBackground(new java.awt.Color(204, 204, 204));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(80, Short.MAX_VALUE)
                .addComponent(pieChart1, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(pieChart1, javax.swing.GroupLayout.PREFERRED_SIZE, 425, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(16, 16, 16))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javaswingdev.chart.PieChart pieChart1;
    // End of variables declaration//GEN-END:variables
}
