/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package forms;

import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import javax.swing.JButton;
import javax.swing.plaf.basic.BasicButtonUI;

/**
 *
 * @author yoaim
 */
public class ChooseStatsForm extends javax.swing.JPanel {

    /**
     * Creates new form ChooseStatsForm
     */
    public ChooseStatsForm() {
        initComponents();
        btnBackground();
    }

    private void btnBackground(){
        JButton [] jButtons = {clientbtn,chambrebtn};
        for (JButton btn : jButtons) {
            btn.setBackground(new Color(21,25,28));
            btn.setUI(new BasicButtonUI());
            btn.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {
                }

                @Override
                public void mousePressed(MouseEvent e) {
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    btn.setBackground(new Color(229, 229, 203));
                    btn.setForeground(Color.BLACK);
                    
               }

                @Override
                public void mouseExited(MouseEvent e) {
                    btn.setBackground(new Color(21,25,28));
                    btn.setForeground(new Color(255,255,255));
                }
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        clientbtn = new javax.swing.JButton();
        pnlCenter = new javax.swing.JPanel();
        chambrebtn = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));
        setPreferredSize(new java.awt.Dimension(800, 550));

        clientbtn.setBackground(new java.awt.Color(21, 25, 28));
        clientbtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        clientbtn.setForeground(new java.awt.Color(255, 255, 255));
        clientbtn.setText("Nombre de clients par année");
        clientbtn.setPreferredSize(new java.awt.Dimension(150, 40));
        clientbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clientbtnActionPerformed(evt);
            }
        });

        pnlCenter.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout pnlCenterLayout = new javax.swing.GroupLayout(pnlCenter);
        pnlCenter.setLayout(pnlCenterLayout);
        pnlCenterLayout.setHorizontalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnlCenterLayout.setVerticalGroup(
            pnlCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 487, Short.MAX_VALUE)
        );

        chambrebtn.setBackground(new java.awt.Color(21, 25, 28));
        chambrebtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        chambrebtn.setForeground(new java.awt.Color(255, 255, 255));
        chambrebtn.setText("Nombre de chambres par catégorie");
        chambrebtn.setPreferredSize(new java.awt.Dimension(150, 40));
        chambrebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chambrebtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(chambrebtn, javax.swing.GroupLayout.PREFERRED_SIZE, 392, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(clientbtn, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(pnlCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(clientbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(chambrebtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void clientbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clientbtnActionPerformed
        // TODO add your handling code here:
        BarChartForm c = new BarChartForm();
        c.setSize(pnlCenter.getSize());
        c.setLocation(0,0);
        
        pnlCenter.removeAll();
        pnlCenter.add(c,BorderLayout.CENTER);
        pnlCenter.revalidate();
        pnlCenter.repaint();
    }//GEN-LAST:event_clientbtnActionPerformed

    private void chambrebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chambrebtnActionPerformed
        // TODO add your handling code here:
         ChartForm c = new ChartForm();
        c.setSize(pnlCenter.getSize());
        c.setLocation(0,0);
        
        pnlCenter.removeAll();
        pnlCenter.add(c,BorderLayout.CENTER);
        pnlCenter.revalidate();
        pnlCenter.repaint();
    }//GEN-LAST:event_chambrebtnActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton chambrebtn;
    private javax.swing.JButton clientbtn;
    private javax.swing.JPanel pnlCenter;
    // End of variables declaration//GEN-END:variables
}
