/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package forms;

import entities.Client;
import entities.LoginConn;
import java.awt.Color;
import java.awt.event.MouseEvent;
import java.awt.event.MouseListener;
import static java.lang.Integer.parseInt;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.plaf.basic.BasicButtonUI;
import javax.swing.table.DefaultTableModel;
import service.ClientService;
import service.LoginConnService;

/**
 *
 * @author yoaim
 */
public class UtilisateurForm extends javax.swing.JPanel {

    /**
     * Creates new form ClientForm
     */
    private LoginConnService  loginConnService = new LoginConnService();
    private DefaultTableModel model;
    private static int id;
    
    public UtilisateurForm() {
        initComponents();
        btnBackground();
        model=(DefaultTableModel)listClients.getModel();
        this.load();
    }

    private void load(){
        model.setRowCount(0);
        for(LoginConn c : loginConnService.findAll()){
            model.addRow(new Object[]{c.getId(),c.getLogin(),c.getPassword()});
        }
    }
    private void btnBackground(){
        JButton [] jButtons = {ajouterbtn,modifierbtn,supprimerbtn};
        for (JButton btn : jButtons) {
            btn.setBackground(new Color(21,25,28));
            btn.setUI(new BasicButtonUI());
            btn.addMouseListener(new MouseListener() {
                @Override
                public void mouseClicked(MouseEvent e) {
                }

                @Override
                public void mousePressed(MouseEvent e) {
                }

                @Override
                public void mouseReleased(MouseEvent e) {
                }

                @Override
                public void mouseEntered(MouseEvent e) {
                    btn.setBackground(new Color(229, 229, 203));
                    btn.setForeground(Color.BLACK);
                    
               }

                @Override
                public void mouseExited(MouseEvent e) {
                    btn.setBackground(new Color(21,25,28));
                    btn.setForeground(new Color(255,255,255));
                }
            });
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        nomtxt = new textfield.TextField();
        prenomtxt = new textfield.TextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        listClients = new table.Table();
        ajouterbtn = new javax.swing.JButton();
        supprimerbtn = new javax.swing.JButton();
        modifierbtn = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        jButton6.setBackground(new java.awt.Color(21, 25, 28));
        jButton6.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(255, 255, 255));
        jButton6.setText("Statistique");
        jButton6.setPreferredSize(new java.awt.Dimension(150, 40));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        setPreferredSize(new java.awt.Dimension(800, 550));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        nomtxt.setLabelText("Login");

        prenomtxt.setLabelText("Mot de passe");

        jScrollPane2.setBackground(new java.awt.Color(255, 255, 255));

        listClients.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Id", "Login", "Mot de passe"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        listClients.setToolTipText("");
        listClients.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                listClientsMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(listClients);

        ajouterbtn.setBackground(new java.awt.Color(21, 25, 28));
        ajouterbtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        ajouterbtn.setForeground(new java.awt.Color(255, 255, 255));
        ajouterbtn.setText("Ajouter");
        ajouterbtn.setPreferredSize(new java.awt.Dimension(150, 40));
        ajouterbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ajouterbtnActionPerformed(evt);
            }
        });

        supprimerbtn.setBackground(new java.awt.Color(21, 25, 28));
        supprimerbtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        supprimerbtn.setForeground(new java.awt.Color(255, 255, 255));
        supprimerbtn.setText("Supprimer");
        supprimerbtn.setPreferredSize(new java.awt.Dimension(150, 40));
        supprimerbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                supprimerbtnActionPerformed(evt);
            }
        });

        modifierbtn.setBackground(new java.awt.Color(21, 25, 28));
        modifierbtn.setFont(new java.awt.Font("Century Gothic", 1, 14)); // NOI18N
        modifierbtn.setForeground(new java.awt.Color(255, 255, 255));
        modifierbtn.setText("Modifier");
        modifierbtn.setPreferredSize(new java.awt.Dimension(150, 40));
        modifierbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modifierbtnActionPerformed(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(21, 25, 28));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 40));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(237, 237, 237)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(nomtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(prenomtxt, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(52, 52, 52)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(supprimerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(modifierbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ajouterbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 758, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(14, Short.MAX_VALUE))
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(ajouterbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(9, 9, 9)
                        .addComponent(modifierbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addComponent(supprimerbtn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(62, 62, 62)
                        .addComponent(nomtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(prenomtxt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 67, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 240, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void ajouterbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ajouterbtnActionPerformed
        // TODO add your handling code here:
        String nom = nomtxt.getText();
        String prenom = prenomtxt.getText();
        if(loginConnService.create(new LoginConn(nom, prenom))){
            this.load();
            nomtxt.setText("");
            prenomtxt.setText("");
            JOptionPane.showMessageDialog(this, "Client bien ajouter");
        }else {
            JOptionPane.showMessageDialog(this, "Client non ajouter");
        }
    }//GEN-LAST:event_ajouterbtnActionPerformed

    private void supprimerbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_supprimerbtnActionPerformed
        // TODO add your handling code here:
      int answer=JOptionPane.showConfirmDialog(this, "Etes vous sur de supprimer ce user?");
        if(answer==0)
           if(loginConnService.delete(loginConnService.findById(id)))
           {
               JOptionPane.showMessageDialog(this,"Client supprimé");
                            load();

           }
    }//GEN-LAST:event_supprimerbtnActionPerformed

    private void modifierbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modifierbtnActionPerformed
        // TODO add your handling code here:
          String nom=nomtxt.getText();
         String prenom=prenomtxt.getText();
         LoginConn loginConn=loginConnService.findById(id);
         loginConn.setLogin(nom);
         loginConn.setPassword(prenom);
         int answer=JOptionPane.showConfirmDialog(this, "Etes vous sur de modifier ce user ?");
         if(answer==0){
             if(loginConnService.update(loginConn)){
                 JOptionPane.showMessageDialog(this,"user modifié");
                            load();
             }
         }
    }//GEN-LAST:event_modifierbtnActionPerformed

    private void listClientsMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listClientsMouseClicked
        // TODO add your handling code here:
            id=parseInt(model.getValueAt(listClients.getSelectedRow(),0).toString());
        nomtxt.setText(model.getValueAt(listClients.getSelectedRow(),1).toString());
        prenomtxt.setText(model.getValueAt(listClients.getSelectedRow(),2).toString());
    }//GEN-LAST:event_listClientsMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouterbtn;
    private javax.swing.JButton jButton6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private table.Table listClients;
    private javax.swing.JButton modifierbtn;
    private textfield.TextField nomtxt;
    private textfield.TextField prenomtxt;
    private javax.swing.JButton supprimerbtn;
    // End of variables declaration//GEN-END:variables
}
